### ISSUE TITLE
pretrained checkpoints

### ISSUE THREAD

**Issue by git-hamza** [NeuroSYS-pl/objects_counting_dmap#11]
Can you provide the pretrained checkpoint if there is no copyrights issues?

**Comment by tgolan-neurosys** [comment]
To be honest, we have not been working on this for a while and we did not keep checkpoints as these models can be trained quite fast. I have just retrained UNet for you and you can download checkpoints from https://data.neurosys.com:4443/minio/public/dmap-models/
