### ISSUE TITLE
infer.py

### ISSUE THREAD

**Issue by HelenaPashnina** [NeuroSYS-pl/objects_counting_dmap#12]
How I can run this part? Maybe I could be wrong...
This is what I am running:
 % python infer.py -n UNet -c cell_FCRN_A.pth -i /Users/elena/Desktop/objects_counting_dmap-master/examples/example_cell.png --visualize

The error:
Traceback (most recent call last):
  File "infer.py", line 128, in <module>
    infer()
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "infer.py", line 83, in infer
    network.load_state_dict(torch.load(checkpoint.name))
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.block1.0.0.weight", "module.block1.0.1.weight", "module.block1.0.1.bias", "module.block1.0.1.running_mean", "module.block1.0.1.running_var", "module.block1.1.0.weight", "module.block1.1.1.weight", "module.block1.1.1.bias", "module.block1.1.1.running_mean", "module.block1.1.1.running_var", "module.block2.0.0.weight", "module.block2.0.1.weight", "module.block2.0.1.bias", "module.block2.0.1.running_mean", "module.block2.0.1.running_var", "module.block2.1.0.weight", "module.block2.1.1.weight", "module.block2.1.1.bias", "module.block2.1.1.running_mean", "module.block2.1.1.running_var", "module.block3.0.0.weight", "module.block3.0.1.weight", "module.block3.0.1.bias", "module.block3.0.1.running_mean", "module.block3.0.1.running_var", "module.block3.1.0.weight", "module.block3.1.1.weight", "module.block3.1.1.bias", "module.block3.1.1.running_mean", "module.block3.1.1.running_var", "module.block4.conv.0.0.0.weight", "module.block4.conv.0.0.1.weight", "module.block4.conv.0.0.1.bias", "module.block4.conv.0.0.1.running_mean", "module.block4.conv.0.0.1.running_var", "module.block4.conv.0.1.0.weight", "module.block4.conv.0.1.1.weight", "module.block4.conv.0.1.1.bias", "module.block4.conv.0.1.1.running_mean", "module.block4.conv.0.1.1.running_var", "module.block5.conv.0.0.0.weight", "module.block5.conv.0.0.1.weight", "module.block5.conv.0.0.1.bias", "module.block5.conv.0.0.1.running_mean", "module.block5.conv.0.0.1.running_var", "module.block5.conv.0.1.0.weight", "module.block5.conv.0.1.1.weight", "module.block5.conv.0.1.1.bias", "module.block5.conv.0.1.1.running_mean", "module.block5.conv.0.1.1.running_var", "module.block6.conv.0.0.0.weight", "module.block6.conv.0.0.1.weight", "module.block6.conv.0.0.1.bias", "module.block6.conv.0.0.1.running_mean", "module.block6.conv.0.0.1.running_var", "module.block6.conv.0.1.0.weight", "module.block6.conv.0.1.1.weight", "module.block6.conv.0.1.1.bias", "module.block6.conv.0.1.1.running_mean", "module.block6.conv.0.1.1.running_var", "module.block7.0.0.weight", "module.block7.0.1.weight", "module.block7.0.1.bias", "module.block7.0.1.running_mean", "module.block7.0.1.running_var", "module.block7.1.0.weight", "module.block7.1.1.weight", "module.block7.1.1.bias", "module.block7.1.1.running_mean", "module.block7.1.1.running_var", "module.density_pred.weight". 
	Unexpected key(s) in state_dict: "module.model.0.0.0.weight", "module.model.0.0.1.weight", "module.model.0.0.1.bias", "module.model.0.0.1.running_mean", "module.model.0.0.1.running_var", "module.model.0.0.1.num_batches_tracked", "module.model.0.1.0.weight", "module.model.0.1.1.weight", "module.model.0.1.1.bias", "module.model.0.1.1.running_mean", "module.model.0.1.1.running_var", "module.model.0.1.1.num_batches_tracked", "module.model.0.2.0.weight", "module.model.0.2.1.weight", "module.model.0.2.1.bias", "module.model.0.2.1.running_mean", "module.model.0.2.1.running_var", "module.model.0.2.1.num_batches_tracked", "module.model.2.0.0.weight", "module.model.2.0.1.weight", "module.model.2.0.1.bias", "module.model.2.0.1.running_mean", "module.model.2.0.1.running_var", "module.model.2.0.1.num_batches_tracked", "module.model.2.1.0.weight", "module.model.2.1.1.weight", "module.model.2.1.1.bias", "module.model.2.1.1.running_mean", "module.model.2.1.1.running_var", "module.model.2.1.1.num_batches_tracked", "module.model.2.2.0.weight", "module.model.2.2.1.weight", "module.model.2.2.1.bias", "module.model.2.2.1.running_mean", "module.model.2.2.1.running_var", "module.model.2.2.1.num_batches_tracked", "module.model.4.0.0.weight", "module.model.4.0.1.weight", "module.model.4.0.1.bias", "module.model.4.0.1.running_mean", "module.model.4.0.1.running_var", "module.model.4.0.1.num_batches_tracked", "module.model.4.1.0.weight", "module.model.4.1.1.weight", "module.model.4.1.1.bias", "module.model.4.1.1.running_mean", "module.model.4.1.1.running_var", "module.model.4.1.1.num_batches_tracked", "module.model.4.2.0.weight", "module.model.4.2.1.weight", "module.model.4.2.1.bias", "module.model.4.2.1.running_mean", "module.model.4.2.1.running_var", "module.model.4.2.1.num_batches_tracked", "module.model.6.0.0.weight", "module.model.6.0.1.weight", "module.model.6.0.1.bias", "module.model.6.0.1.running_mean", "module.model.6.0.1.running_var", "module.model.6.0.1.num_batches_tracked", "module.model.6.1.0.weight", "module.model.6.1.1.weight", "module.model.6.1.1.bias", "module.model.6.1.1.running_mean", "module.model.6.1.1.running_var", "module.model.6.1.1.num_batches_tracked", "module.model.6.2.0.weight", "module.model.6.2.1.weight", "module.model.6.2.1.bias", "module.model.6.2.1.running_mean", "module.model.6.2.1.running_var", "module.model.6.2.1.num_batches_tracked", "module.model.8.0.0.weight", "module.model.8.0.1.weight", "module.model.8.0.1.bias", "module.model.8.0.1.running_mean", "module.model.8.0.1.running_var", "module.model.8.0.1.num_batches_tracked", "module.model.8.1.0.weight", "module.model.8.1.1.weight", "module.model.8.1.1.bias", "module.model.8.1.1.running_mean", "module.model.8.1.1.running_var", "module.model.8.1.1.num_batches_tracked", "module.model.8.2.0.weight", "module.model.8.2.1.weight", "module.model.8.2.1.bias", "module.model.8.2.1.running_mean", "module.model.8.2.1.running_var", "module.model.8.2.1.num_batches_tracked", "module.model.10.0.0.weight", "module.model.10.0.1.weight", "module.model.10.0.1.bias", "module.model.10.0.1.running_mean", "module.model.10.0.1.running_var", "module.model.10.0.1.num_batches_tracked", "module.model.10.1.0.weight", "module.model.10.1.1.weight", "module.model.10.1.1.bias", "module.model.10.1.1.running_mean", "module.model.10.1.1.running_var", "module.model.10.1.1.num_batches_tracked", "module.model.10.2.0.weight", "module.model.10.2.1.weight", "module.model.10.2.1.bias", "module.model.10.2.1.running_mean", "module.model.10.2.1.running_var", "module.model.10.2.1.num_batches_tracked", "module.model.12.0.0.weight", "module.model.12.0.1.weight", "module.model.12.0.1.bias", "module.model.12.0.1.running_mean", "module.model.12.0.1.running_var", "module.model.12.0.1.num_batches_tracked", "module.model.12.1.0.weight", "module.model.12.1.1.weight", "module.model.12.1.1.bias", "module.model.12.1.1.running_mean", "module.model.12.1.1.running_var", "module.model.12.1.1.num_batches_tracked", "module.model.12.2.0.weight", "module.model.12.2.1.weight", "module.model.12.2.1.bias", "module.model.12.2.1.running_mean", "module.model.12.2.1.running_var", "module.model.12.2.1.num_batches_tracked".

**Comment by tgolan-neurosys** [comment]
`-n UNet -c cell_FCRN_A.pth`

it looks like you are trying to run UNet architecture with weights from FCRN
