### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by piks2252** [NeuroSYS-pl/objects_counting_dmap#13]
Hello,
Can I use my own custom dataset?

Thanks

**Comment by abitrolly** [comment]
Yes. Why not? Have you tried it?

**Comment by piks2252** [comment]
Yes, I tried it but while training it gives me everything 0. Please check the below image
![Screenshot from 2022-04-07 18-45-56](https://user-images.githubusercontent.com/41064348/162255217-35f8bab0-1745-4bb9-92e0-0aa468585891.png)

Maybe it is happening because in the cells dataset the object is masked by 1 pixel and in my dataset whole object is masked. Please check the below image

![101dots](https://user-images.githubusercontent.com/41064348/162255794-67eb270c-32f0-4069-89e0-812918adb0e9.png)
Cells mask image

![5dots](https://user-images.githubusercontent.com/41064348/162255891-cc9ff920-5186-45e5-aaa5-46459bb47340.png)
Custom dataset mask image

I am not sure, If I am right then what should I do? Do I need to make my dataset mask image like the cells dataset mask image?

Thanks

**Comment by abitrolly** [comment]
> I am not sure, If I am right then what should I do? Do I need to make my dataset mask image like the cells dataset mask image?

The only thing that I see is to try it, indeed.

**Comment by piks2252** [comment]
I tried it the same way and now I got every value like average loss, error,... but when I try to count objects from images it gives me a negative value.

**Comment by tgolan-neurosys** [comment]
Yes, you can use this method for your data, but you need to prepare data properly.

Please refer to our article for the details: https://neurosys.com/objects-counting-by-estimating-a-density-map (there are references to the original papers, where this method for counting was introduced).
