### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by ghost** [NeuroSYS-pl/objects_counting_dmap#2]
Hello, I find your repo very interesting and helpful. Could you please upload your inference code? Thank you

**Comment by ghost** [comment]
Could you please provide your inference code ? Coz your code is not quite intuitive

**Comment by tgolan-neurosys** [comment]
There is no plan to provide an inference code at this moment. However, one can easily run a model on a test set using the same procedure as used for validation. Also, it should be straightforward to extract appropriate parts of code from the validation loop to prepare an inference.

**Comment by abitrolly** [comment]
https://github.com/NeuroSYS-pl/objects_counting_dmap/commit/a7d4a43992efa4ab16cfc2ac11c2457a73411d03 )
