### ISSUE TITLE
About the feat in Mall?

### ISSUE THREAD

**Issue by ZachZou-logs** [NeuroSYS-pl/objects_counting_dmap#3]
Hello, thank you for your code. I have a question about the Mall, in many places, we should make use of the feat to build roi, but I don't find any operation about the feat. So can you tell me how to deal with the roi in the dataset of Mall ?
Looking forward your reply!

**Comment by tgolan-neurosys** [comment]
ROI is not used in this approach. The method implemented here is described here: https://neurosys.com/article/objects-counting-by-estimating-a-density-map-with-convolutional-neural-networks/
