### ISSUE TITLE
Can you provide infer.py for inference from image?

### ISSUE THREAD

**Issue by mactiendinh** [NeuroSYS-pl/objects_counting_dmap#9]
I hope you will provide infer.py for inference from image.
Thank you !

**Comment by tgolan-neurosys** [comment]
Done

**Comment by abitrolly** [comment]
Thanks Tomasz. https://github.com/NeuroSYS-pl/objects_counting_dmap/commit/a7d4a43992efa4ab16cfc2ac11c2457a73411d03 is much better than [the crappy code I've written](https://github.com/abitrolly/ai_people_counter/blob/inferhack/get_output.py). :D
